[package]
name = "feign-common"
version = "0.1.2"
edition = "2021"
authors = ["niuhuan <niuhuancn@outlook.com>"]
description = "Rest client of Rust"
license = "MIT"
repository = "https://github.com/niuhuan/feign-rs"

[dependencies]
serde = "1"
serde_derive = "1"
serde_json = "1"

[lib]
