[package]
name = "feign-macros"
version = "0.1.0"
edition = "2021"
authors = ["niuhuan <niuhuancn@outlook.com>"]
description = "Rest client of Rust"
license = "MIT"

[dependencies]
darling = "0"
proc-macro-error = "1"
proc-macro2 = "1"
quote = "1"
syn = "1"

[lib]
proc-macro = true
