[package]
name = "feign"
version = "0.1.5"
edition = "2021"
authors = ["niuhuan <niuhuancn@outlook.com>"]
description = "Rest client of Rust"
license = "MIT"
repository = "https://github.com/niuhuan/feign-rs"

[dependencies]
serde_json = "1"
feign-macros = { path = "../feign-macros" }

[lib]
