[package]
name = "feign"
version = "0.1.0"
edition = "2021"
authors = ["niuhuan <niuhuancn@outlook.com>"]
description = "Rest client of Rust"
license = "MIT"
repository = "https://github.com/niuhuan/feign-rs"

[dependencies]
feign-macros = "0.1.0"

[lib]
